import = [
  "~/.config/alacritty/catppuccin-frappe.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10}
dynamic_padding = true
decorations = "Full" # Linux: None | Mac: Transparent
opacity = 0.90
blur = true
# Options: "Maximized", "Fullscreen", "SimpleFullscreen"
startup_mode = "Windowed" 
dynamic_title = true

[font]
size = 15.5
# normal = {family = "FiraCode Nerd Font Mono", style = "Medium"} # Make sure font is installed

