set-option -sa terminal-overrides ",xterm*:Tc"

###################
#### Keybinds ####
##################

# Set prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Bind config source
unbind r
bind r source-file ~/.dotFiles/configs/home/.tmux.conf

# Bind vertical pane
unbind %
bind | split-window -h -c "#{pane_current_path}"

# Bind horizontal pane
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Custom splits
bind h split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"


# Bind vim nav 
unbind Left
unbind Right
unbind Up
unbind Down

bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5
bind -r C-h resize-pane -L 5

bind -r m resize-pane -Z

# Enable mouse support
set -g mouse on

# don't exit copy mode when dragging with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane 

# Handle terminal output vi navigation 
set-window-option -g mode-keys vi

bind -T copy-mode-vi v send-keys -X begin-selection
#Different ways to copy from tmux to clipboard
#bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"
#bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

####################
#### Status Bar ####
####################


#####################
#### Plugin List ####
#####################

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Rose Pine Color Theme 
set -g @plugin 'rose-pine/tmux'

set -g @rose_pine_variant 'moon' # Options are 'main', 'moon' or 'dawn'

# NOTE: LEAVE THIS AT THE BOTTOM
run '~/.tmux/plugins/tpm/tpm'
