preload = /home/ponder/.dotFiles/wallpapers/rose_pine/moon_fern.png

# Catch all approach, but wasnt consistent for my monitor
#wallpaper = , /home/ponder/.dotFiles/wallpapers/rose_pine/moon_fern.png

wallpaper = DP-1, /home/ponder/.dotFiles/wallpapers/rose_pine/moon_fern.png
wallpaper = eDP-1, /home/ponder/.dotFiles/wallpapers/rose_pine/moon_fern.png
